language: csharp
  mono: none
  dotnet: 2.1.302
  install:
    - yarn
  script:
    - yarn build-ext
    - yarn test
    - dotnet restore src/server/VDFServer/VDFServer/VDFServer.csproj
    - dotnet build src/server/VDFServer/VDFServer/VDFServer.csproj
