matrix:
  include:
    - language: node_js
      node_js: "lts/*"
      install:
        - yarn
      before_script:
        - yarn build-ext
      script:
        - yarn test
  include:
    language: csharp
    mono: none
    dotnet: 2.1.302
    install:
      - dotnet restore src/server/VDFServer/VDFServer/VDFServer.csproj
    script:
      - dotnet build src/server/VDFServer/VDFServer/VDFServer.csproj
