<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>vw</string>
		<string>rv</string>
		<string>sl</string>
		<string>dg</string>
		<string>src</string>
		<string>dd</string>
		<string>pkg</string>
		<string>mod</string>
		<string>cls</string>
		<string>CLS</string>
		<string>bpo</string>
		<string>rpt</string>
		<string>mnu</string>
		<string>cal</string>
		<string>con</string>
	</array>
	<key>name</key>
	<string>VDF</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>match</key>
			<string>(//.*)</string>
			<key>name</key>
			<string>comment.line.double-slash</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\(</string>
			<key>name</key>
			<string>string.unquoted</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\)</string>
			<key>name</key>
			<string>string.unquoted</string>
		</dict>
		<dict>
			<key>match</key>
			<string>'.*?'</string>
			<key>name</key>
			<string>string.quoted.single</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>"</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.begin</string>
				</dict>
			</dict>
			<key>end</key>
			<string>"</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.end</string>
				</dict>
			</dict>
			<key>name</key>
			<string>string.quoted.double</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?i)\b((0(x|X)[0-9a-fA-F]*)|(([0-9]+\.?[0-9]*)|(\.[0-9]+))((e|E)(\+|-)?[0-9]+)?)([LlFfUuDd]|UL|ul)?\b</string>
			<key>name</key>
			<string>constant.numeric</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?i)^\s*(\w*):</string>
			<key>name</key>
			<string>constant.language</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.function</string>
				</dict>
			</dict>
		</dict>
		<dict>
			<key>match</key>
			<string>(?i)(\bObject\b\s(\w*\b)(\s*\w*\b){3})</string>
			<key>name</key>
			<string>constant.language</string>
			<key>captures</key>
			<dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.function</string>
				</dict>
			</dict>
		</dict>
		<dict>
			<key>match</key>
			<string>(?i)External_Function (\b\w*\b)</string>
			<key>name</key>
			<string>constant.language</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.function</string>
				</dict>
			</dict>
		</dict>
		<dict>
			<key>match</key>
			<string>(?i)#COMMAND\s*(\w*\b)</string>
			<key>name</key>
			<string>constant.language</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.function</string>
				</dict>
			</dict>
		</dict>
		<dict>
			<key>match</key>
			<string>(?i)#ENDCOMMAND\s*(\w*\b)</string>
			<key>name</key>
			<string>constant.language</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.function</string>
				</dict>
			</dict>
		</dict>
		<dict>
			<key>match</key>
			<string>(?i)(\bClass\b\s(\w*\b)(\s*\w*\b){3})</string>
			<key>name</key>
			<string>constant.language</string>
			<key>captures</key>
			<dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.function</string>
				</dict>
			</dict>
		</dict>
		<dict>
			<key>match</key>
			<string>(?i)(\bStruct\b\s(\w*\b))</string>
			<key>name</key>
			<string>constant.language</string>
			<key>captures</key>
			<dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.function</string>
				</dict>
			</dict>
		</dict>
		<dict>
			<key>match</key>
			<string>(?i)(\bEnd_Struct\b)</string>
			<key>name</key>
			<string>constant.language</string>
			<key>captures</key>
			<dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.function</string>
				</dict>
			</dict>
		</dict>
		<dict>
			<key>match</key>
			<string>(?i)(\bCD_Popup_Object\b\s(\w*\b)(\s*\w*\b){3})</string>
			<key>name</key>
			<string>constant.language</string>
			<key>captures</key>
			<dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.function</string>
				</dict>
			</dict>
		</dict>
		<dict>
			<key>match</key>
			<string>(?i)(\bHCSS_CD_Object\b\s(\w*\b)(\s*\w*\b){3})</string>
			<key>name</key>
			<string>constant.language</string>
			<key>captures</key>
			<dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.function</string>
				</dict>
			</dict>
		</dict>
		<dict>
			<key>match</key>
			<string>(?i)(\b(Procedure|Procedure_Section)\b\s(Set\s)?(\w*\b)([^/]*))</string>
			<key>name</key>
			<string>constant.language</string>
			<key>captures</key>
			<dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>entity.name.function</string>
				</dict>
			</dict>
		</dict>
		<dict>
			<key>match</key>
			<string>(?i)(\bFunction\b\s(Get\s)?(\w*\b)([^/]*))</string>
			<key>name</key>
			<string>constant.language</string>
			<key>captures</key>
			<dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>entity.name.function</string>
				</dict>
			</dict>
		</dict>
		<dict>
			<key>match</key>
			<string>(?i)(\bEnd_Object|Cd_End_Object\b)</string>
			<key>name</key>
			<string>constant.language</string>
			<key>captures</key>
			<dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.function</string>
				</dict>
			</dict>
		</dict>
		<dict>
			<key>match</key>
			<string>(?i)(\bEnd_Procedure\b)</string>
			<key>name</key>
			<string>constant.language</string>
			<key>captures</key>
			<dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>entity.name.function</string>
				</dict>
			</dict>
		</dict>
		<dict>
			<key>match</key>
			<string>(?i)(\bEnd_Class\b)</string>
			<key>name</key>
			<string>constant.language</string>
			<key>captures</key>
			<dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.function</string>
				</dict>
			</dict>
		</dict>
		<dict>
			<key>match</key>
			<string>(\bEnd_Function\b)</string>
			<key>name</key>
			<string>constant.language</string>
			<key>captures</key>
			<dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>entity.name.function</string>
				</dict>
			</dict>
		</dict>
		<dict>
			<key>match</key>
			<string>(?i)\b(Number|Integer|String|Boolean|Date|Handle|DateTime)\b</string>
			<key>name</key>
			<string>storage.type</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?i)\b(Begin_Row|End_Row|Enumeration_List|End_Enumeration_List|Enum_List|End_Enum_List)\b</string>
			<key>name</key>
			<string>support.function</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?i)\b(Case|Constrain|Property)\b</string>
			<key>name</key>
			<string>support.function</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?i)\b(Use|Send|Sysdate|Get|Set|Index|Clear|Find|Move|Showln|Found|On_Key|Increment|Entry_Item|Add|Register_Object|Register_Function|Register_Procedure|Import_Class_Protocol)\b</string>
			<key>name</key>
			<string>support.function</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?i)\b(Procedure_Return|Forward|Function_Return|Begin|End|While|Repeat|Loop|If|Else|For_All|End_For_All|\w*Deferred_View|Until|Delegate)\b</string>
			<key>name</key>
			<string>support.function</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?i)\b(False|True|Self)\b</string>
			<key>name</key>
			<string>support.function</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?i)\b(Write|Writeln|Left|Right|Mid|For|Runprogram|shell|Close_Output|Direct_Output|Append_Output|Ordering|Define)\b</string>
			<key>name</key>
			<string>support.function</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?i)\b(SaveRecord|Unlock|Reread|Repeat)\b</string>
			<key>name</key>
			<string>support.function</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?i)\b(eq|ge|gt|le|=|&lt;|&gt;|ne|&lt;&gt;|&gt;=|&lt;=|and|or|lt)\b</string>
			<key>name</key>
			<string>keyword.operator.comparison</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(\-|\+|\*|\/|%)</string>
			<key>name</key>
			<string>keyword.operator.arithmetic</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?i)\b(for|is|a|to|not|do|continue|rgb|of|by|from)\b</string>
			<key>name</key>
			<string>keyword.other</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?i)\b.*\.dd\b|\b.*\.DD\b</string>
			<key>name</key>
			<string>constant.language</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?i)\b.*\.vw\b</string>
			<key>name</key>
			<string>constant.language</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?i)\b.*\.rpt[\b][^"]</string>
			<key>name</key>
			<string>constant.language</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?i)\b.*\.bpo\b</string>
			<key>name</key>
			<string>constant.language</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?i)\b.*\.sl\b</string>
			<key>name</key>
			<string>constant.language</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?i)\b.*\.pkg\b</string>
			<key>name</key>
			<string>constant.language</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?i)\b.*\.dg\b</string>
			<key>name</key>
			<string>constant.language</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?i)\b.*\.mod\b</string>
			<key>name</key>
			<string>constant.language</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?i)\b.*\.cls\b</string>
			<key>name</key>
			<string>constant.language</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.vdf</string>
	<key>uuid</key>
	<string>ef4d85e8-a2aa-4c09-b7fc-c2683ea10d81</string>
</dict>
</plist>
